import React from 'react'

function Terms() {
    return (
        <div className="bg-cover bg-back-img">
            <div className="pl-10 pr-10 pt-8 pb-7">
                <h1 className="text-white items-center justify-center pl-16 lg:pl-96 xl:pl-96 xl:ml-36 font-semibold text-xl">Terms And Conditions</h1>
                <div className="pt-6">
                    <div className="bg-gray-700 text-white">
                        <div className="pl-6 pr-6 pt-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Definition</h1>
                            <p className="text-sm">1.1. The following rules and regulations apply to the use, connection and participation of users (collectively"ROYAL.WIN", as the case may be) on the Internet“ Play Cash” provided by the website and other websites operated by the website ; Gambling Services (& quot; Gambling Services & quot;). This rule must be consistent with the rules of the game for a particular game (collectively" gaming rules") and other rules applicable to the use and connection of gaming services and gaming software to the gaming site and the gaming information contained in them (collectively" this article" ;) Read them together.<br/><br/>1.2. " Gambling " For the purposes of this article, including, but not limited to, betting, games and various gambling activities through any and / or all gambling services provided through the gambling website;
" Connected device " means any application connected device, but not limited to personal computers, laptops, mobile phones, personal digital assistants, PDA phones, and portable devices used to use and connect to gaming sites and participate in gaming services.
" Gambling Software " means a computer program, data file, or any other information and information content (including any user information related to it) installed on a user-connected device approved by the regulatory authority, so that the user can use the device through the user-connected device , Connect and participate in the gaming services offered on the gaming site;
" Sportsbook " means the Internet betting system accessed and / or provided under the Sportsbook " Sportsbook " link / title, and all related services and online gambling activities.</p>
                        </div>
                        <div className="pl-6 pr-6 pt-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Agree</h1>
                            <p className="text-sm">2.1. During the registration process, the user “I confirm that I am at least 18 years old, and have read, printed and agreed to this rule” in the box after the words, and click the corresponding "Save and continue" Button, the user confirms and agrees:
The user has read, fully understood and agreed to these Terms and Conditions; and these Terms and Conditions constitute a legally binding agreement between the user and ROYAL.WIN regarding the use of the gaming service (" Usage Agreement ").<br/><br/>2.2. If the user does not agree with any of the provisions of this article, please tick the "I do not agree" button, and please do not click the "Save and Continue" button, and do not attempt to use or continue to use any gaming services or download and / Or install gaming software.</p>
                        </div>
                        <div className="pl-6 pr-6 pt-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Modify</h1>
                            <p className="text-sm">3.1. We reserve the absolute right to amend, update and modify this Regulation and the Gaming Rules (or any part thereof) at any time. Any such amendments, updates or modifications will be posted on the gaming site. The amended, updated or modified rules and betting rules will become effective when they are posted on the betting website. The user shall continue to use, link and participate in the gambling services through the gambling website and gambling equipment after the above amendments, updates or modifications are announced, the user shall be deemed to have agreed to and accepted the revised or updated regulations and gambling rules.<br/><br/>3.2. The user acknowledges and agrees that the user is solely responsible for reviewing the aforementioned amendments, updates and / or modifications. ROYAL.WIN has the discretion to notify users of such amendments, updates and modifications. The above amendments, updates and modifications may be notified to users from time to time at the discretion of ROYAL.WIN. ROYAL.WIN has no obligation to notify users of the above-mentioned amendments, updates and modifications.</p>
                        </div>
                        <div className="pl-6 pr-6 pt-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Gaming Information And Intellectual Property</h1>
                            <p className="text-sm">4.1. Information, materials and data provided through gaming websites, gaming services, gaming equipment and / or any other means, made available to users, accessible to users, generated and / or collected, including but not limited to marketing plans and materials, results , Statistical data, event data and schedule, probability and betting data, text, icons, audiovisual information (" betting information"), are owned by the licensors of ROYAL.WIN and / or ROYAL.WIN, and are for users' personal use Commercial purpose.<br/><br/>4.2. Except as expressly provided in this Article, without the prior written consent of us or the third party data owner, the user shall not adapt, copy, modify, duplicate, store, distribute, display, publicly play, Make cable programs, publish, transmit, sell, lend, rent, license, use gambling information or otherwise make available, use, or Connect with the gaming information above.<br/><br/>4.3. Enjoy copyright, trademark and other forms of intellectual property and patent protection on the gaming website and / or gaming software, gaming services and gaming information provided through connected devices. All rights, title and interest in the gaming software, gaming services and gaming information on the gaming site are owned by, licensed to, or controlled by the ROYAL.WIN and / or ROYAL.WIN licensor. The User acknowledges that the User has not obtained any rights, benefits or licenses to the aforementioned gaming software, gaming services and gaming information by using or linking to the gaming software, gaming services and gaming information provided on the gaming website and / or through the connected device.</p>
                        </div>
                        <div className="pl-6 pr-6 pt-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Conditions Of Use</h1>
                            <p className="text-sm">5.1. As a condition of using the gaming service, the user warrants and promises that the user shall not use or link the gaming website, gaming service, gaming software for any purpose that violates any laws applicable to the user, violates this regulation and / or is prohibited by this regulation And / or gaming information. In addition to all other statements and guarantees listed in this article, the user hereby further warrants and promises that as a condition of using the gaming service:<br/>Due to national and regional legal restrictions, we do not accept registration and betting in the Philippines, Taiwan, Korea, the United States, Singapore, Hong Kong, the United Kingdom, France, Germany, Guadeloupe, Guyana, Martinique and Reunion.
Users carry out activities in their own identity and name, rather than trading on behalf of others;
Unlimited legal capacity of users;<br/>The user has not been diagnosed or identified as gambling obsessive-compulsive disorder;
The user's age is (a) at least 18 years old; or (b) has reached any other legal age or adult age required by the laws applicable to the user, whichever is greater (“ legal age”);<br/> Users fully understand the risk of losing funds in the process of using the gaming service;
The money deposited by the user does not originate from criminal or other illegal, unauthorized or licensed activities;
The user is not engaged in criminal or other illegal, unauthorized or licensed activities and / or attempts to use the user's account opened at ROYAL.WIN to engage in the above activities; the user shall not use or allow others to use the gaming service or the user's gaming account to engage in the user or Any criminal or other illegal activity required by any of our laws, including but not limited to money laundering;
Keep the user ’s account name, account number and password confidential to prevent illegal connection or use, and immediately change the password or notify us if the account name, account number or password is compromised in any way;
Responsible for any and all activities of connecting and using the gambling services through the gambling website and / or connection device with the user's account name, account number and password, regardless of whether the above connection and / or use is authorized by or known to the user; <br/> Do not use gaming services, gaming websites, connected devices, gaming software and gaming information in any way that interferes with or may interfere with other users ’use of gaming services and gaming websites, and does not implement any behavior that reduces or may reduce the operating efficiency of gaming services and gaming websites;
Do not solicit or attempt in any way to obtain any information about other users;
Do not upload or distribute any programs, files, or data that contain viruses, have been destroyed, or may affect the performance of connected devices, gaming software, gaming services, and / or gaming websites;
The user's connection or use of the gambling services and gambling information through the gambling website and / or connected device does not violate the laws applicable to the user; nor does it violate the contract that is binding on the user or the owner of the country where the user currently connects to the betting website or uses the connected device Obligations; at the same time not prohibited by the aforementioned legal or contractual obligations;
Do not use any equipment, machinery, device, software, program or other method (or anything of the nature described above) to interfere with or attempt to interfere with gaming services, connected devices, gaming software, gaming websites, gaming information or gaming websites and / or connected devices The normal operation of any transaction provided;
Not post or transmit any illegal, harassing, abusive, threatening, defamatory, defamatory, obscene, obscene, seditious, racist, pornographic or vulgar content to the gaming site and / or connected device or any other user, Or content that could constitute or abet crimes, trigger civil liability, or otherwise violate any law;
The user is not a manager, director, employee, consultant, affiliate or agent of ROYAL.WIN or any of its affiliates, or has a relative or same-dwelling relationship with any of the above; and
Does not interfere with other users' use of gaming services, gaming websites, gaming software, connected devices and / or gaming information or initiating and / or participating in surveys, contests, chain letters or posting / transmitting“ spam” or other unsolicited mass distribution mail.</p>
                        </div>
                        <div className="pl-6 pr-6 pt-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Register To Open A Gaming Account And Membership</h1>
                            <p className="text-sm">If you choose not to provide your Personal Data it may prevent us from meeting legal obligations, fulfilling a contract, or performing services required to run your account. Not providing your Personal Data may mean we are unable to provide you with products or services.</p>
                        </div>
                        <div className="pl-6 pr-6 pt-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Information Collected</h1>
                            <p className="text-sm">6.1. In order to participate in gambling and use gambling services through ROYAL.WIN, users must complete the application for opening an account and membership in accordance with the procedures described on the gambling website (“ Membership Application”).
6.2. The user declares and promises that all information provided by the user when registering and processing the membership application, including the user name (“ name”), source of funds (including relevant bank account number and card number), and residential address , True, accurate and complete in all respects.
6.3. #SiteName will take necessary and appropriate measures to maintain the confidentiality of personal data that users disclose to us. We will keep the personal data and betting information of users received strictly confidential, except as required by laws, regulations, rules, courts or regulators or any relevant gaming management or law enforcement agency or decision or decision or as required by this rule. Users are responsible for the confidentiality of their personal data. We reserve the right to disclose user personal data to our payment settlement service providers and financial institutions to the extent necessary to complete the payment procedures for the gaming services provided on the gaming website.
6.4. The user is also responsible for ensuring that the user's use and connection to the gaming website and the gambling information contained therein, downloading and installing gambling software, and / or using and participating in the gambling service are not prohibited by laws applicable to the user.
6.5. In order to verify the user's membership application, we also need the user to provide proof of identity and age (such as a valid ID with photo and debit or credit card). If there is any change in the specific original information provided by the user, we should promptly notify us. In order to confirm the user's name and address, ROYAL.WIN reserves the right to confirm the user's name and address by mail. ROYAL.WIN may also use its own discretion to verify any information provided by the user. The user agrees to this rule, which also means that he agrees to ROYAL.WIN connection, use, processing and storage of any authentication or verification results of the user.
6.6. We reserve the absolute right to reject user membership applications for any reason.
We are only responsible for the ROYAL.WIN official alternate website published by the Online Instant Help. Members will not bear any responsibility for any loss caused by logging in to any other link that looks like ROYAL.WIN. If you have any other questions, please contact our online customer service directly

6.7. Users can only open one account at ROYAL.WIN. If we find that the user has opened more than one account in ROYAL.WIN, we reserve the right to handle all of the user's accounts in ROYAL.WIN as a consolidated account at our discretion, to cancel redundant accounts or to terminate this agreement with the user.</p>
                        </div>
                        <div className="pl-6 pr-6 pt-6 pb-6">
                            <h1 className="text-yellow-300 text-lg font-semibold">Place And Accept Bets</h1>
                            <p className="text-sm">7.1. Games, sporting events and other gaming activities that we offer from time to time on the gaming site and / or through connected devices are open to users to place bets. Users are required to place bets in accordance with the gaming rules for specific games or gaming activities and the provisions of this article. In the event of any gambling player showing an obvious error or showing an error, all bets on that gamble will be void. In the event of a ROYAL.WIN gaming system failure, ROYAL.WIN also reserves the right to declare any or all bets void.
7.2. Although there may be other provisions in this rule, ROYAL.WIN reserves the right to refuse all or part of the user's bet at its discretion for any reason.
7.3. We only accept bets placed by users via the Internet and / or connected devices in accordance with this clause. No other form of betting (mail, email, fax, etc.) will be accepted. Even if we receive another form of bet, it will be considered invalid regardless of the result of the last bet.
#SiteName has the right to freeze or cancel its account when it finds that the customer violates the rules, terms or in a sense of fraud, illegal intrusion, attack, forgery or damage to normal gaming rules. All resulting winnings, bonuses and all account balances will be frozen and forfeited. ROYAL.WIN does not require any advance notice.
Any unusual bets will be cancelled without notice. It is hereby declared that the use of artificial intelligence or software (bots“ bots”) in online betting services is strictly prohibited, and any attempt or use of this method will be cancelled and the relevant account will be closed immediately.

7.4. Subject to other provisions of this article, if the user enters the correct username and password and there is sufficient balance in the account, the user will effectively place a bet code.
7.5. The user is responsible for all activities and transactions using the following (or a combination of them) (regardless of whether the following uses are authorized):
User name; and / or
User account n
nd / or
The user's username and password.

7.6. Users are solely responsible for ensuring the accuracy of their betting details. Subject to other provisions of this article, once the user places a bet and we confirm that the user's bet is accepted, it is the final confirmation of the user's bet; the user must not cancel, withdraw or change the bet details.
7.7. All bets are recorded in the transaction log database. # siteName's transaction record is the ultimate confirmation of all transactions and relevant information on betting.
7.8. Subject to other provisions of this article, when the transaction code appears on the user's screen and is effectively displayed in the user's transaction history, the bet is deemed valid and accepted by ROYAL.WIN.
7.9. No bets may be placed after the start of the match and / or when the result of the match is known. #SiteName reserves the right to reject a user's bet or declare the bet to be invalid without notifying the user if the match is still in error and the user is aware of the result of the bet when the bet was placed. #SiteName The discretion to accept all or part of such bets. For the avoidance of doubt, this clause does not exclude" in the second half" bets (" in play" bets) or“ half time” bets (" half time" bets).
7.10. The scheduled start time on the gaming site is for informational purposes only. If ROYAL.WIN inadvertently accepts bets after the start of the game for any reason, ROYAL.WIN reserves the right to cancel and declare such bets invalid.
7.11. Unless specific rules regarding games and games provide otherwise, for gambling purposes, the outcome of a bet on a game or game will be determined on the day the game or game actually ends. ROYAL.WIN does not recognize any subsequent inquiries that may lead to the overturning of the above results, and the original payout is still valid.
7.12. If the venue of a sporting event changes, all bets based on the original arena will be void.
7.13. The winner of the game or game will be determined on the day the game or game actually ends in accordance with the gaming rules.
7.14. For the purpose of betting, ROYAL.WIN does not recognize any results of postponed matches, protests or overthrows.
7.15. If the user's multiple prizes include non-entrant options or invalid options, the payout will be settled based on the remaining valid options.
7.16. The user acknowledges that all odds, indices and handicaps may fluctuate without notice. The above-mentioned odds, indexes and handicaps are only determined when the user bets are accepted by us.
7.17. If the user's betting odds, index or handicap is incorrect due to obvious errors or system failure, the user's bet or multi-bet part of the bet is invalid. If relevant errors or malfunctions are corrected in a timely manner, ROYAL.WIN reserves the right (but not the obligation) to decide to make reasonable efforts to contact the user to allow the user to re-bet with the correct odds, index and handicap.
7.18. We do not accept users to bet on the same event at the same time.
7.19. In the case of any bet and its related transactions, ROYAL.WIN shall have the final decision and the decision made shall be final and conclusive.</p>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Terms
